name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.1
      - run: composer install
      - run: mkdir ~/.ssh && echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
      - run: echo 'GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"' > .env && cat .env.dist >> .env
      - run: git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"
      - run: bin/build
      - run: bin/build --deploy --no-component-update
        if: ${{ github.ref == 'refs/heads/main' }}
